# hide-cursor-when-typing = false
# ignore-selection-foreground-color = false
theme = "lovelace"
padding-x = 10
padding-y = [10, 0]
# line-height = 1.2
# working-dir = "/Users/raphael/Documents/"
# env-vars = []
# use-fork = false
confirm-before-quit = false

#[cursor]
#shape = 'beam'

[editor]
program = "nvim"
# args = []

[window]
x = 562
y = 1400
width = 1350
height = 440
mode = "windowed"
opacity = 0.95
blur = true
decorations = "disabled"
# colorspace = "display-p3"

[renderer]
performance = "high"
backend = "automatic"

# [keyboard]
# use-kitty-keyboard-protocol = false
# disable-ctlseqs-alt = false
# ime-cursor-positioning = true

[fonts]
size = 14
family = "Liga SFMono Nerd Font"

# [scroll]
# multiplier = 3.0
# divider = 1.0

# Navigation
#
# "mode" - Define navigation mode
#   • NativeTab (MacOS only)
#   • Bookmark
#   • BottomTab
#   • TopTab
#   • Plain
#
# "hide-if-single" - Hide navigation UI if is single.
# "clickable" - Enable click on tabs to switch.
# "use-current-path" - Use same path whenever a new tab is created (Note: requires `use-fork` to be set to false).
# "color-automation" - Set a specific color for the tab whenever a specific program is running, or in a specific directory.
#
# Example:
[navigation]
mode = "bottomtab"
use-split = false
# clickable = false
hide-if-single = false
# use-current-path = false
# color-automation = []

# https://raphamorim.io/rio/docs/key-bindings
# [bindings]
# keys = [
#   { key = "q", with = "super", action = "Quit" },
#   # Bytes[27, 91, 53, 126] is equivalent to "\x1b[5~"
#   { key = "home", with = "super | shift", bytes = [27, 91, 53, 126] }
# ]

